name: "🚀 release"

on:
  push:
    branches: [master]

jobs:
  release:
    name: 🚀 release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: 🚀 publish
      - run: npm i
      - run: npm run build
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
